### PR TITLE
Allow change generated folder name

### PR DESCRIPTION
**Pull request by AurimarL**
Allow users to set the name for the __generated folder using surql-gen.json

### CODE REVIEW

**Comment by hammo92** [comment]
Thanks for the pull request @AurimarL. I'm struggling to see the use case for this as the files in the __generated are only used internally. Could you give me an example of when you might need to change the directory name?

**Comment by AurimarL** [comment]
Hello @hammo92,

Thank you for taking the time to review my merge request.

Summary: I have been working on a boilerplate for integrating Next.js with SurrealDB. My goal is to align this project closely with the functionality provided by [TDBM](https://thecodingmachine.github.io/tdbm/).
 
Captura de ecrã 2024-08-08 142627

Reason for the Merge Request: I am exploring the possibility of relating this library with the SurrealDB migration library. I believe this integration could lead to more contributions or even a potential fork of the library in the future.

Thank you for your consideration, and I look forward to your feedback!

Best regards,

**Comment by hammo92** [comment]
Okay, I'm still not sure why you would need to use the _generated folder directly rather than use the exports from the schema folder. I'm not familiar with TDBM or the migration library you're referring to; can you summarise how being able to rename the generated folder simplifies integration?

**Comment by sebastianwessel** [comment]
The usage of the internal `__generated` folder like this is not recommended - especially as it is removed/overwritten on each run.
Because of this, I will close the PR, as this won't make it in the lib.

**Pull request closed without merging**
