### PR TITLE
Object fixes and tests

### PR DESCRIPTION
**Pull request by hammo92**
Fixes for objects:
Set optional correctly on object if definitions is `option<object>`
If all object are values are optional we set the object to optional
Handle objects in arrays recursively

Add tests

### CODE REVIEW

**Review by sebastianwessel — APPROVED** [review]

**Comment by sebastianwessel** [comment]
@hammo92 awesome work 🚀
I invited you to the repo to give you some collaborator access.
Is the merge button clickable for you?

**Comment by hammo92** [comment]
> Should fix #37 ?

Should do, I used those definitions in the test cases.

**Comment by hammo92** [comment]
> @hammo92 awesome work 🚀 I invited you to the repo to give you some collaborator access. Is the merge button clickable for you?

Yeah, it is. Any changes needed or are we good to merge?

**Comment by sebastianwessel** [comment]
Free to fire - Your work, you should press the button... 🎉

**Comment by sebastianwessel** [comment]
Is it than maybe time for a new release, or is there something you like to add/change before release? @hammo92

**Comment by hammo92** [comment]
Seems like a good time for a new release, think with the object fixes we're pretty stable. Until the next bug pops up!

**Comment by sebastianwessel** [comment]
[version 2.5 is out](https://github.com/sebastianwessel/surrealdb-client-generator/releases/tag/v2.5.0)

**Pull request merged**
